# permissions for end users to edit supervisedgits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: supervisedgit-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: syn3
    app.kubernetes.io/part-of: syn3
    app.kubernetes.io/managed-by: kustomize
  name: supervisedgit-editor-role
rules:
- apiGroups:
  - syn.servicenow.com
  resources:
  - supervisedgits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syn.servicenow.com
  resources:
  - supervisedgits/status
  verbs:
  - get
